backend:
  name: git-gateway
  branch: netlify-cms

media_folder: static/media_root
public_folder: /media_root

collections:
  - name: 'articles'
    label: 'articles'
    format: 'json'
    folder: 'content/articles'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'Heroes'
    label: 'heroes'
    folder: 'content/heroes'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Headline', name: 'headline', widget: 'string' }
      - label: 'Videos'
        label_singular: 'Video'
        name: 'videos'
        required: true
        widget: 'list'
        summary: '{{fields.type}} - {{fields.src}}'
        fields:
          - { label: 'Type', name: 'type', widget: 'string', hint: 'Type of video, example: video/mp4' }
          - { label: 'Src', name: 'src', widget: 'file' }

  - name: 'Navigation'
    label: 'navigation'
    description: 'Navigation menu'
    delete: false
    editor:
      preview: false
    files:
      - label: 'Menu'
        name: 'menu'
        file: 'content/navigation/navs.json'
        format: 'json'
        widget: 'list'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'To', name: 'to', widget: 'string', hint: 'Navigation link, example: /the-vessel'}
          - label: 'Children'
            name: 'children'
            widget: 'list'
            summary: '{{fields.title}} - {{fields.to}}'
            hint: 'Navigation Children'
            default: []
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'To', name: 'to', widget: 'string' }
