backend:
  name: git-gateway
  branch: netlify-cms

media_folder: static/media_root
public_folder: /media_root

collections:
  - label: 'Articles'
    name: 'articles'
    format: 'json'
    folder: 'content/articles'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Navigation'
    name: 'navigation'
    description: 'Navigation menu'
    delete: false
    files:
      - label: 'Menu'
        name: 'menu'
        file: 'content/navigation/menu.yaml'
        fields:
          - name: menu
            label: Menu
            widget: list
            fields:
            - { label: 'Title', name: 'title', widget: 'string' }
            - { label: 'To', name: 'to', widget: 'string', hint: 'Navigation link, example: /the-vessel'}
            - label: 'Children'
              name: 'children'
              widget: 'list'
              summary: 'Title: {{fields.title}}, to: {{fields.to}}'
              hint: 'Navigation Children'
              default: []
              fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'To', name: 'to', widget: 'string' }

  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'content/pages/home.yaml'
        fields:
          - label: 'Hero'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'markdown' }
              - label: 'Videos'
                label_singular: 'Video'
                name: 'videos'
                widget: 'list'
                summary: '{{fields.type}} - {{fields.src}}'
                fields:
                  - { label: 'Type', name: 'type', widget: 'string', hint: 'Type of video, example: video/mp4' }
                  - { label: 'Src', name: 'src', widget: 'file' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Mobile Image', name: 'mobile_image', widget: 'image' }

          - label: 'Section Intro'
            name: 'intro'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'markdown' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { image: 'Image', name: 'image', widget: 'image' }
