backend:
  name: git-gateway
  branch: netlify-cms

media_folder: static/media_root
public_folder: /media_root

collections:
  - label: 'Articles'
    name: 'articles'
    format: 'json'
    folder: 'content/articles'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Navigation'
    name: 'navigation'
    description: 'Navigation menu'
    delete: false
    editor:
      preview: false
    files:
      - label: 'Menu'
        name: 'menu'
        file: 'content/navigation/menu.yaml'
        fields:
          - name: menu
            label: Menu
            widget: list
            fields:
            - { label: 'Title', name: 'title', widget: 'string' }
            - { label: 'To', name: 'to', widget: 'string', hint: 'Navigation link, example: /the-vessel'}
            - label: 'Children'
              name: 'children'
              widget: 'list'
              summary: 'Title: {{fields.title}}, to: {{fields.to}}'
              hint: 'Navigation Children'
              default: []
              fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'To', name: 'to', widget: 'string' }

  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'content/pages/home.yaml'
        fields:
          - label: 'Hero'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'markdown' }
              - label: 'Videos'
                label_singular: 'Video'
                name: 'videos'
                widget: 'list'
                summary: '{{fields.type}} - {{fields.src}}'
                fields:
                  - { label: 'Type', name: 'type', widget: 'string', hint: 'Type of video, example: video/mp4' }
                  - { label: 'Src', name: 'src', widget: 'file' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Mobile Image', name: 'mobile_image', widget: 'image' }
          - label: 'Section Intro'
            name: 'intro'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'markdown' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { image: 'Image', name: 'image', widget: 'image' }
          - label: 'Section The Vessel'
            name: 'the_vessel'
            widget: 'object'
            fields:
              - { label: 'Caption', name: 'caption', widget: 'string' }
              - { label: 'Heading', name: 'heading', widget: 'markdown' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'To', name: 'to', widget: 'string', hint: 'Button link.' }
          - label: 'Section Voyages'
            name: 'voyages'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - label: 'Tabs Data'
                name: 'tabs_data'
                widget: 'list'
                min: 1
                summary: '{{fields.name}}'
                fields:
                  - { label: 'Tab name', name: 'name', widget: 'string' }
                  - label: 'Tab Content'
                    name: 'data'
                    widget: 'object'
                    fields:
                      - { label: 'Heading', name: 'heading', widget: 'string' }
                      - { label: 'Description', name: 'description', widget: 'markdown' }
                      - { label: 'Image', name: 'image', widget: 'image' }
                      - { label: 'To', name: 'to', widget: 'string', hint: 'Button link.' }
          - label: 'Section Dining'
            name: 'dining'
            widget: 'object'
            fields:
              - { label: 'Caption', name: 'caption', widget: 'string' }
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'to', name: 'to', widget: 'string', hint: 'Button link.'}
          - label: 'Section Occasions'
            name: 'occasios'
            widget: 'object'
            fields:
              - { label: 'Caption', name: 'caption', widget: 'string' }
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'to', name: 'to', widget: 'string', hint: 'Button link.'}

      - label: 'The Vessel Page'
        name: 'vessel'
        file: 'content/pages/vessel.yaml'
        fields:
          - label: 'Hero'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Mobile Image', name: 'mobile_image', widget: 'image' }
          - label: 'Section Intro'
            name: 'intro'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'markdown' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Youtube id', name: 'youtube_id', widget: 'string' }
          - label: 'Section suites & Staterooms'
            name: 'suites_and_staterooms'
            widget: 'object'
            fields:
              - { label: 'Caption', name: 'caption', widget: 'string' }
              - { label: 'Heading', name: 'heading', widget: 'markdown' }
              - { label: 'To', name: 'to', hint: 'Button link.' }
              - label: 'Slider Data'
                name: 'data'
                widget: 'list'
                summary: '{{fields.heading}}'
                fields:
                  - { label: 'Heading', name: 'heading', widget: 'string' }
                  - { label: 'Description', name: 'description', widget: 'markdown' }
                  - { label: 'Image', name: 'image', widget: 'image' }
          - label: 'Section The Decks'
            name: 'the_decks'
            widget: 'list'
            summary: '{{fields.heading}}'
            fields:
              - { label: 'Caption', name: 'caption', widget: 'string' }
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'To', name: 'to', widget: 'string', hint: 'Button link.' }
          - label: 'Section The Teams'
            name: 'teams'
            widget: 'object'
            fields:
              - { label: 'Caption', name: 'caption', widget: 'string' }
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - label: 'Slider Data'
                name: 'data'
                widget: 'list'
                summary: '{{fields.name}} - {{fields.title}}'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Name', name: 'name', widget: 'string' }
                  - { label: 'Image', name: 'image', widget: 'image' }
          - label: 'Section Sustainability'
            name: 'sustainability'
            widget: 'object'
            fields:
              - { label: 'Caption', name: 'caption', widget: 'string' }
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'To', name: 'to', hint: 'Button link.' }

      - label: 'Suites & Staterooms Page'
        name: 'suites-and-staterooms'
        file: 'content/pages/suites-and-staterooms.yaml'
        fields:
          - label: 'Hero'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Mobile Image', name: 'mobile_image', widget: 'image' }
